version: "3.7"

services:
  # Qdrant Vector Database for testing
  qdrant-test:
    container_name: qdrant_test
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant-test-data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  test-network:
    driver: bridge

volumes:
  qdrant-test-data: