# Minimal SearXNG configuration for testing with bot detection disabled
use_default_settings: true

general:
  instance_name: "SearXNG Test"
  debug: false  # Disable debug to avoid forced limiter

search:
  # Limit search engines for faster test startup
  safe_search: 0
  default_lang: "en"
  ban_time_on_fail: 0
  max_ban_time_on_fail: 10
  formats:
    - html
    - json  # Enable both HTML and JSON formats

server:
  limiter: false  # Disable rate limiting for tests
  public_instance: false  # Disable public instance features to avoid forced limiter
  secret_key: "test-secret-key"
  method: "GET"
  port: 8080  # Default port (mapped to 8081 externally)
  
# Disable bot detection completely
enabled_plugins: []

# Minimal engines for testing
engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

# Disable most outgoing requests for faster tests
outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0
  pool_connections: 10
  pool_maxsize: 10

# Redis configuration for test environment
redis:
  url: valkey://valkey-test:6379/0