# Qdrant Configuration for Crawl4AI MCP Server
service:
  # API configuration
  http_port: 6333
  grpc_port: 6334
  
  # Performance settings
  max_request_size_mb: 32
  max_workers: 0  # Auto-detect optimal worker count
  
  # Enable web UI
  enable_static_content: true
  
storage:
  # Storage configuration
  storage_path: /qdrant/storage
  
  # Performance optimizations
  on_disk_payload: true
  
  # WAL configuration
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
    
  # Optimizers
  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size: 200000
    memmap_threshold: 50000
    indexing_ram: 256
    flush_interval_sec: 5
    max_optimization_threads: 1
    
  # HNSW Index configuration  
  hnsw_index:
    m: 16
    ef_construct: 100
    full_scan_threshold: 10000
    max_indexing_threads: 0
    on_disk: false
    payload_m: null
    
  # Quantization
  quantization:
    always_ram: false

# Cluster configuration (disabled for single node)
cluster:
  enabled: false

# Telemetry
telemetry:
  telemetry_disabled: true